# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: fuota/fuota.proto for package 'ChirpStackAPI.Common'

require 'grpc'
require 'fuota/fuota_pb'

module ChirpStackAPI
  module Common
    module FUOTAServerService
      # FUOTAServerService provides the fuota-server API methods.
      # Note: this API considered experimental.
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'fuota.FUOTAServerService'

        # CreateDeployment creates the given FUOTA deployment.
        rpc :CreateDeployment, ::ChirpStackAPI::Common::CreateDeploymentRequest, ::ChirpStackAPI::Common::CreateDeploymentResponse
        # GetDeploymentStatus returns the FUOTA deployment status given an ID.
        rpc :GetDeploymentStatus, ::ChirpStackAPI::Common::GetDeploymentStatusRequest, ::ChirpStackAPI::Common::GetDeploymentStatusResponse
        # GetDeploymentDeviceLogs returns the FUOTA logs given a deployment ID and DevEUI.
        rpc :GetDeploymentDeviceLogs, ::ChirpStackAPI::Common::GetDeploymentDeviceLogsRequest, ::ChirpStackAPI::Common::GetDeploymentDeviceLogsResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
